version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://optimizer:8000
    depends_on:
      - optimizer

  optimizer:
    build:
      context: ./sketch_running_order
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sketch_running_order:/app
    environment:
      - PYTHONUNBUFFERED=1
