version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./sketches.db:/app/sketches.db  # Persist the SQLite DB file
    environment:
      - VITE_API_URL=http://optimizer:8000
    depends_on:
      - optimizer

  optimizer:
    build:
      context: ./sketch_running_order
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sketch_running_order:/app
    environment:
      - PYTHONUNBUFFERED=1
